# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcc
from rcc.models.od_mcomplex_type_definition_annotation import ODMcomplexTypeDefinitionAnnotation  # noqa: E501
from rcc.rest import ApiException

class TestODMcomplexTypeDefinitionAnnotation(unittest.TestCase):
    """ODMcomplexTypeDefinitionAnnotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ODMcomplexTypeDefinitionAnnotation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcc.models.od_mcomplex_type_definition_annotation.ODMcomplexTypeDefinitionAnnotation()  # noqa: E501
        if include_optional :
            return ODMcomplexTypeDefinitionAnnotation(
                comment = rcc.models.od_mcomplex_type_definition_comment.ODMcomplexTypeDefinitionComment(
                    value = '0', 
                    sponsor_or_site = 'SPONSOR', ), 
                flag = [
                    rcc.models.od_mcomplex_type_definition_flag.ODMcomplexTypeDefinitionFlag(
                        flag_value = rcc.models.od_mcomplex_type_definition_flag_value.ODMcomplexTypeDefinitionFlagValue(
                            value = '0', 
                            code_list_oid = '0', ), 
                        flag_type = rcc.models.od_mcomplex_type_definition_flag_type.ODMcomplexTypeDefinitionFlagType(
                            value = '0', 
                            code_list_oid = '0', ), )
                    ], 
                seq_num = 56, 
                transaction_type = 'INSERT', 
                id = '0'
            )
        else :
            return ODMcomplexTypeDefinitionAnnotation(
        )

    def testODMcomplexTypeDefinitionAnnotation(self):
        """Test ODMcomplexTypeDefinitionAnnotation"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
