# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rcc
from rcc.api.study_groups_controller_api import StudyGroupsControllerApi  # noqa: E501
from rcc.rest import ApiException


class TestStudyGroupsControllerApi(unittest.TestCase):
    """StudyGroupsControllerApi unit test stubs"""

    def setUp(self):
        self.api = rcc.api.study_groups_controller_api.StudyGroupsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create10(self):
        """Test case for create10

        Create new Study Group Class for current Study based on auth token provided  # noqa: E501
        """
        pass

    def test_create_bulk_academic(self):
        """Test case for create_bulk_academic

        Create new Study Group Class for current Study based on auth token provided  # noqa: E501
        """
        pass

    def test_delete7(self):
        """Test case for delete7

        Delete Study Group Class for current Study based on auth token provided  # noqa: E501
        """
        pass

    def test_get_details7(self):
        """Test case for get_details7

        Get specified Study Group Class details  # noqa: E501
        """
        pass

    def test_get_group_class_subject_assignments(self):
        """Test case for get_group_class_subject_assignments

        Get available subject assignments  # noqa: E501
        """
        pass

    def test_get_group_class_types(self):
        """Test case for get_group_class_types

        Get available study types  # noqa: E501
        """
        pass

    def test_get_list8(self):
        """Test case for get_list8

        Get list of all Study Group Classes for specified Study  # noqa: E501
        """
        pass

    def test_update9(self):
        """Test case for update9

        Update Study Group Classes for current Study based on auth token provided  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
