# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rcc
from rcc.api.audit_logs_controller_api import AuditLogsControllerApi  # noqa: E501
from rcc.rest import ApiException


class TestAuditLogsControllerApi(unittest.TestCase):
    """AuditLogsControllerApi unit test stubs"""

    def setUp(self):
        self.api = rcc.api.audit_logs_controller_api.AuditLogsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_audit_codes_event_type_list(self):
        """Test case for get_audit_codes_event_type_list

        Get list of all Event Types in Audit log  # noqa: E501
        """
        pass

    def test_get_audit_log_items_list(self):
        """Test case for get_audit_log_items_list

        Get filtered list of Audit log records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
