# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcc
from rcc.models.crf_subject_filter import CrfSubjectFilter  # noqa: E501
from rcc.rest import ApiException

class TestCrfSubjectFilter(unittest.TestCase):
    """CrfSubjectFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CrfSubjectFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcc.models.crf_subject_filter.CrfSubjectFilter()  # noqa: E501
        if include_optional :
            return CrfSubjectFilter(
                event_definition_ids = [
                    56
                    ], 
                crf_versions = [
                    56
                    ], 
                crfs = [
                    56
                    ], 
                subject_ids = [
                    56
                    ], 
                subject_unique_ids = [
                    '0'
                    ], 
                subject_randomization_ids = [
                    '0'
                    ], 
                subject_screening_ids = [
                    '0'
                    ]
            )
        else :
            return CrfSubjectFilter(
        )

    def testCrfSubjectFilter(self):
        """Test CrfSubjectFilter"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
