# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcc
from rcc.models.todm_export_options import TodmExportOptions  # noqa: E501
from rcc.rest import ApiException

class TestTodmExportOptions(unittest.TestCase):
    """TodmExportOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TodmExportOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcc.models.todm_export_options.TodmExportOptions()  # noqa: E501
        if include_optional :
            return TodmExportOptions(
                study_site_id = 56, 
                subjects = [
                    '0'
                    ], 
                events = [
                    '0'
                    ], 
                crf_forms = [
                    '0'
                    ], 
                crf_versions = [
                    '0'
                    ], 
                sites = [
                    '0'
                    ], 
                date_from = '0', 
                date_to = '0'
            )
        else :
            return TodmExportOptions(
        )

    def testTodmExportOptions(self):
        """Test TodmExportOptions"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
