# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcc
from rcc.models.od_mcomplex_type_definition_audit_records import ODMcomplexTypeDefinitionAuditRecords  # noqa: E501
from rcc.rest import ApiException

class TestODMcomplexTypeDefinitionAuditRecords(unittest.TestCase):
    """ODMcomplexTypeDefinitionAuditRecords unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ODMcomplexTypeDefinitionAuditRecords
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcc.models.od_mcomplex_type_definition_audit_records.ODMcomplexTypeDefinitionAuditRecords()  # noqa: E501
        if include_optional :
            return ODMcomplexTypeDefinitionAuditRecords(
                audit_record = [
                    rcc.models.od_mcomplex_type_definition_audit_record.ODMcomplexTypeDefinitionAuditRecord(
                        user_ref = rcc.models.od_mcomplex_type_definition_user_ref.ODMcomplexTypeDefinitionUserRef(
                            user_oid = '0', ), 
                        location_ref = rcc.models.od_mcomplex_type_definition_location_ref.ODMcomplexTypeDefinitionLocationRef(
                            location_oid = '0', ), 
                        date_time_stamp = rcc.models.od_mcomplex_type_definition_date_time_stamp.ODMcomplexTypeDefinitionDateTimeStamp(
                            value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        reason_for_change = rcc.models.od_mcomplex_type_definition_reason_for_change.ODMcomplexTypeDefinitionReasonForChange(
                            value = '0', ), 
                        source_id = rcc.models.od_mcomplex_type_definition_source_id.ODMcomplexTypeDefinitionSourceID(
                            value = '0', ), 
                        edit_point = 'MONITORING', 
                        used_imputation_method = 'YES', 
                        id = '0', )
                    ]
            )
        else :
            return ODMcomplexTypeDefinitionAuditRecords(
        )

    def testODMcomplexTypeDefinitionAuditRecords(self):
        """Test ODMcomplexTypeDefinitionAuditRecords"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
