# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rcc
from rcc.api.cr_fs_controller_api import CRFsControllerApi  # noqa: E501
from rcc.rest import ApiException


class TestCRFsControllerApi(unittest.TestCase):
    """CRFsControllerApi unit test stubs"""

    def setUp(self):
        self.api = rcc.api.cr_fs_controller_api.CRFsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create2(self):
        """Test case for create2

        Create new CRF and CRF version for current Study based on auth token provided  # noqa: E501
        """
        pass

    def test_get_crf_details(self):
        """Test case for get_crf_details

        Get CRF details for current Study based on auth token provided  # noqa: E501
        """
        pass

    def test_get_crf_versions(self):
        """Test case for get_crf_versions

        Get CRF Versions for current CRF and Study  # noqa: E501
        """
        pass

    def test_get_list1(self):
        """Test case for get_list1

        Get list of all CRFs for specified study  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
