# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcc
from rcc.models.record_survey_assignment import RecordSurveyAssignment  # noqa: E501
from rcc.rest import ApiException

class TestRecordSurveyAssignment(unittest.TestCase):
    """RecordSurveyAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RecordSurveyAssignment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcc.models.record_survey_assignment.RecordSurveyAssignment()  # noqa: E501
        if include_optional :
            return RecordSurveyAssignment(
                participant_id = '0', 
                participant_dob = '0', 
                participant_initials = '0', 
                participant_email = '0', 
                redcap_study_group_name = '0', 
                redcap_event_name = '0', 
                redcap_survey_identifier = '0', 
                participant_screening_number = '0', 
                redcap_survey_link = '0'
            )
        else :
            return RecordSurveyAssignment(
        )

    def testRecordSurveyAssignment(self):
        """Test RecordSurveyAssignment"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
