# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcc
from rcc.models.survey_event_definition_view_rpc import SurveyEventDefinitionViewRpc  # noqa: E501
from rcc.rest import ApiException

class TestSurveyEventDefinitionViewRpc(unittest.TestCase):
    """SurveyEventDefinitionViewRpc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SurveyEventDefinitionViewRpc
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcc.models.survey_event_definition_view_rpc.SurveyEventDefinitionViewRpc()  # noqa: E501
        if include_optional :
            return SurveyEventDefinitionViewRpc(
                id = 56, 
                crf_id = 56, 
                crf_name = '0', 
                study_id = 56, 
                survey_title = '0', 
                survey_id = 56, 
                event_definition_id = 56, 
                event_definition_name = '0', 
                disp_sequence = 56
            )
        else :
            return SurveyEventDefinitionViewRpc(
        )

    def testSurveyEventDefinitionViewRpc(self):
        """Test SurveyEventDefinitionViewRpc"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
