# coding: utf-8

"""
    nPhase REST Resource

    REDCap REST API v.2  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcc
from rcc.models.rule_target_section import RuleTargetSection  # noqa: E501
from rcc.rest import ApiException

class TestRuleTargetSection(unittest.TestCase):
    """RuleTargetSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RuleTargetSection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcc.models.rule_target_section.RuleTargetSection()  # noqa: E501
        if include_optional :
            return RuleTargetSection(
                name = '0', 
                crf_name = '0', 
                crf_version = '0'
            )
        else :
            return RuleTargetSection(
        )

    def testRuleTargetSection(self):
        """Test RuleTargetSection"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
